### ISSUE TITLE
CallbackReturn does not name a type

### ISSUE THREAD

**Issue by JacobJBeck** [ros2/demos#281]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Binaries
- Version or commit hash:
  - 79b0aa08ac59b785da067fecb9b0b12e5c7b1fd9
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Pull and execute `colcon build`

#### Expected behavior
Demos build

#### Actual behavior
Get multiple errors of the form
```
/home/jacob/ros2_ws/src/demos/lifecycle/src/lifecycle_talker.cpp:106:62: error: ‘CallbackReturn’ in ‘class rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface’ does not name a type
   rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
```

**Comment by sloretz** [comment]
`CallbackReturn` was added very recently on the master branch of `rclcpp` in https://github.com/ros2/rclcpp/pull/555 .

It looks like you got an error when building master of this repository with an earlier release. To build a version of demos that works checkout the `bouncy` or `ardent` branch.

https://github.com/ros2/demos/tree/bouncy
https://github.com/ros2/demos/tree/ardent

If you would like to build master, then all dependencies need to be on master as well. See `Building from source` on the installation page on the wiki https://github.com/ros2/ros2/wiki/Installation .

I'll close this since I think that explains the issue, but feel free to comment here still.
