### ISSUE TITLE
crystal branch?

### ISSUE THREAD

**Issue by lucasw** [ros2/demos#310]
6d348de1f5c225bc0896facb463bc660b00b2464 doesn't build with crystal:

```
.../demos/intra_process_demo/src/cyclic_pipeline/cyclic_pipeline.cpp: In constructor ‘IncrementerPipe::IncrementerPipe(const string&, const string&, const string&)’:
.../demos/intra_process_demo/src/cyclic_pipeline/cyclic_pipeline.cpp:30:24: error: ‘NodeOptions’ is not a member of ‘rclcpp’
   : Node(name, rclcpp::NodeOptions().use_intra_process_comms(true))
```

The previous f2ad8eba721bc4a71d9017f271db5da3898da0e9 does.  Could there be a crystal branch made off of that commit, which would be built with https://github.com/ros2/rclcpp/tree/crystal rather than https://github.com/ros2/rclcpp/tree/master?

**Comment by nuclearsandwich** [comment]
>  Could there be a crystal branch made off of that commit

This is the likely case. @mjcarroll and @wjwwood based on discussion yesterday I'm pretty sure this is an intentional API change. I'm going to create the crystal branch and update the distro and release track but give me a shout if there's a backward-compatible solution I'm missing.

**Comment by wjwwood** [comment]
There is no backwards compatible alternative, no. This was an intentional breaking change.

> [6d348de](https://github.com/ros2/demos/commit/6d348de1f5c225bc0896facb463bc660b00b2464) doesn't build with crystal:

In general, I would not recommend to use the master branch of any specific repository and try to build it against an existing release. We have a released version of this repository for crystal which is guaranteed to work. If you want to build master of this repository then you should build master of everything. Mixing the two is going to get you into trouble most of the time.

**Comment by lucasw** [comment]
https://github.com/ros2/demos/tree/crystal exists now.

**Comment by nuclearsandwich** [comment]
> In general, I would not recommend to use the master branch of any specific repository

Prior to branching for crystal using `rosinstall_generator --rosdistro crystal --upstream-development ...` would pull the master branch of demos as we didn't do a blanket branch for crystal. From where I'm sitting this means we've been getting the benefit of bugfixes without manual backports with some sacrifice to "nightly" stability of the upstream development branches. To me this has been worth it but I don't speak for everyone.

**Comment by wjwwood** [comment]
> From where I'm sitting this means we've been getting the benefit of bugfixes without manual backports with some sacrifice to "nightly" stability of the upstream development branches.

Well, all I'm saying is that using master rather than "upstream-devel" of crystal has the benefits of bug fixes and stability (we rarely break our master builds as they are tested nightly and need to pass to merge pr's).

If you're keen on using `rosinstall_generator`, then we should have a dashing rosdistro already with a the source entries setup for all of them so you can do `rosinstall_generator --rosdistro dashing --upstream-development ...`. We'd discussed a "rolling" or "latest" distro for ROS 1 at some point. It could fulfill the same role.

In the meantime, you can use crystal and then a "master" from a single repository (as was done here) as an advanced use case, but I wouldn't be surprised if it doesn't work and I'd fallback to one of the other approaches when it doesn't.
